// src/services/fecap-partners.ts
import type { Company } from "../types";

const FECAP_LOGO_BASE_URL =
  "https://www.fecap.br/files/icon/svg/marcas";

export const fecapPartnerCompanies: Company[] = [
  {
    id: "au-pair",
    name: "Au Pair",
    logo: `${FECAP_LOGO_BASE_URL}/logo-aupair.svg`,
    industry: "Intercâmbio e educação",
    description:
      "Empresa parceira da FECAP com oportunidades relacionadas a intercâmbio, educação e desenvolvimento internacional.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Intercâmbio", "Educação"],
  },
  {
    id: "bayer",
    name: "Bayer",
    logo: `${FECAP_LOGO_BASE_URL}/logo-bayer.svg`,
    industry: "Ciências da vida",
    description:
      "Empresa parceira da FECAP com atuação em saúde, agricultura, tecnologia e inovação.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Saúde", "Tecnologia", "Inovação"],
  },
  {
    id: "bdo",
    name: "BDO",
    logo: `${FECAP_LOGO_BASE_URL}/logo-bdo.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, contabilidade, finanças, tecnologia e consultoria.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Auditoria", "Contabilidade", "Consultoria"],
  },
  {
    id: "becomex",
    name: "Becomex",
    logo: `${FECAP_LOGO_BASE_URL}/logo-becomex.svg`,
    industry: "Tecnologia e comércio exterior",
    description:
      "Empresa parceira da FECAP especializada em tecnologia, comércio exterior, tributação e processos empresariais.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Tecnologia", "Comércio exterior"],
  },
  {
    id: "bradesco",
    name: "Bradesco",
    logo: `${FECAP_LOGO_BASE_URL}/logo-bradesco.svg`,
    industry: "Serviços financeiros",
    description:
      "Instituição financeira parceira da FECAP com oportunidades em negócios, finanças, dados, segurança e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Banco", "Finanças", "Tecnologia"],
  },
  {
    id: "braskem",
    name: "Braskem",
    logo: `${FECAP_LOGO_BASE_URL}/logo-braskem.svg`,
    industry: "Indústria química",
    description:
      "Empresa parceira da FECAP com atuação industrial e oportunidades em negócios, engenharia, dados e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Indústria", "Engenharia", "Tecnologia"],
  },
  {
    id: "companhia-de-estagios",
    name: "Companhia de Estágios",
    logo: `${FECAP_LOGO_BASE_URL}/logo-comp-estagios.svg`,
    industry: "Recrutamento e seleção",
    description:
      "Parceira da FECAP especializada em programas de estágio, trainee e recrutamento de jovens talentos.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Estágio", "Trainee", "Recrutamento"],
  },
  {
    id: "crowe",
    name: "Crowe",
    logo: `${FECAP_LOGO_BASE_URL}/logo-crowe-horwath.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, riscos, finanças, tecnologia e consultoria.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Auditoria", "Riscos", "Consultoria"],
  },
  {
    id: "cummins",
    name: "Cummins",
    logo: `${FECAP_LOGO_BASE_URL}/logo-cummins.svg`,
    industry: "Indústria e tecnologia",
    description:
      "Empresa parceira da FECAP com oportunidades nas áreas industrial, administrativa, financeira e tecnológica.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Indústria", "Tecnologia"],
  },
  {
    id: "deloitte",
    name: "Deloitte",
    logo: `https://upload.wikimedia.org/wikipedia/commons/7/72/DeloitteNewLogo.jpg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, consultoria, dados, cibersegurança e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: [
      "FECAP",
      "Auditoria",
      "Consultoria",
      "Dados",
      "Cibersegurança",
    ],
  },
  {
    id: "dentsu",
    name: "Dentsu",
    logo: `${FECAP_LOGO_BASE_URL}/logo-dentsu.svg`,
    industry: "Publicidade e comunicação",
    description:
      "Empresa parceira da FECAP com oportunidades em publicidade, marketing, mídia, dados e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Marketing", "Publicidade", "Dados"],
  },
  {
    id: "dia",
    name: "DIA",
    logo: `${FECAP_LOGO_BASE_URL}/logo-dia.svg`,
    industry: "Varejo",
    description:
      "Empresa parceira da FECAP com oportunidades em varejo, operações, administração, logística e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Varejo", "Operações", "Logística"],
  },
  {
    id: "duratex",
    name: "Duratex",
    logo: `${FECAP_LOGO_BASE_URL}/logo-duratex.svg`,
    industry: "Indústria",
    description:
      "Empresa parceira da FECAP com oportunidades nas áreas administrativa, industrial, financeira e tecnológica.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Indústria", "Administração"],
  },
  {
    id: "endeavor",
    name: "Endeavor",
    logo: `${FECAP_LOGO_BASE_URL}/logo-endavor.svg`,
    industry: "Empreendedorismo",
    description:
      "Organização parceira da FECAP voltada a empreendedorismo, inovação, negócios e desenvolvimento de lideranças.",
    isFecapPartner: true,
    partnershipType: "academic",
    recommendationBoost: 20,
    tags: ["FECAP", "Empreendedorismo", "Inovação"],
  },
  {
    id: "ey",
    name: "EY",
    logo: `${FECAP_LOGO_BASE_URL}/logo-ey.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, consultoria, contabilidade, dados e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Auditoria", "Consultoria", "Tecnologia"],
  },
  {
    id: "google",
    name: "Google",
    logo: `${FECAP_LOGO_BASE_URL}/logo-google.svg`,
    industry: "Tecnologia",
    description:
      "Empresa parceira da FECAP com atuação em tecnologia, produtos digitais, dados, inteligência artificial e negócios.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 25,
    tags: ["FECAP", "Tecnologia", "Dados", "IA"],
  },
  {
    id: "grant-thornton",
    name: "Grant Thornton",
    logo: `${FECAP_LOGO_BASE_URL}/logo-grantthornton.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, contabilidade, consultoria e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Auditoria", "Contabilidade", "Consultoria"],
  },
  {
    id: "honda",
    name: "Honda",
    logo: `${FECAP_LOGO_BASE_URL}/logo-honda.svg`,
    industry: "Indústria automotiva",
    description:
      "Empresa parceira da FECAP com oportunidades em negócios, indústria, engenharia, finanças e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Automotivo", "Indústria", "Tecnologia"],
  },
  {
    id: "hope",
    name: "Hope",
    logo: `${FECAP_LOGO_BASE_URL}/logo-hope.svg`,
    industry: "Moda e varejo",
    description:
      "Empresa parceira da FECAP com oportunidades em moda, varejo, marketing, administração e comércio eletrônico.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Moda", "Varejo", "E-commerce"],
  },
  {
    id: "itau",
    name: "Itaú Unibanco",
    logo: `${FECAP_LOGO_BASE_URL}/logo-itau.svg`,
    industry: "Serviços financeiros",
    description:
      "Instituição financeira parceira da FECAP com oportunidades em negócios, finanças, dados, produtos e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Banco", "Finanças", "Dados", "Tecnologia"],
  },
  {
    id: "jwt",
    name: "JWT",
    logo: `${FECAP_LOGO_BASE_URL}/logo-jtw.svg`,
    industry: "Publicidade e comunicação",
    description:
      "Empresa parceira da FECAP com oportunidades em publicidade, comunicação, marketing e estratégia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Publicidade", "Marketing", "Comunicação"],
  },
  {
    id: "kpmg",
    name: "KPMG",
    logo: `${FECAP_LOGO_BASE_URL}/logo-kpmg.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, consultoria, contabilidade, riscos e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Auditoria", "Consultoria", "Riscos"],
  },
  {
    id: "lenovo",
    name: "Lenovo",
    logo: `${FECAP_LOGO_BASE_URL}/logo-lenovo.svg`,
    industry: "Tecnologia",
    description:
      "Empresa parceira da FECAP com oportunidades em tecnologia, produtos, vendas, operações e inovação.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 25,
    tags: ["FECAP", "Tecnologia", "Produtos", "Inovação"],
  },
  {
    id: "mastercard",
    name: "Mastercard",
    logo: `${FECAP_LOGO_BASE_URL}/logo-mastercard.svg`,
    industry: "Tecnologia financeira",
    description:
      "Empresa parceira da FECAP com oportunidades em pagamentos, finanças, dados, segurança e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 25,
    tags: ["FECAP", "Fintech", "Pagamentos", "Tecnologia"],
  },
  {
    id: "m-camilo",
    name: "M. Camilo",
    logo: `${FECAP_LOGO_BASE_URL}/logo-mcamilo.svg`,
    industry: "Serviços empresariais",
    description:
      "Empresa parceira da FECAP com oportunidades profissionais e aproximação com a comunidade acadêmica.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Parceira institucional"],
  },
  {
    id: "medley",
    name: "Medley",
    logo: `${FECAP_LOGO_BASE_URL}/logo-medley.svg`,
    industry: "Farmacêutica",
    description:
      "Empresa parceira da FECAP com oportunidades em saúde, administração, finanças, operações e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Saúde", "Farmacêutica"],
  },
  {
    id: "nestle",
    name: "Nestlé",
    logo: `${FECAP_LOGO_BASE_URL}/logo-nestle.svg`,
    industry: "Alimentos e bebidas",
    description:
      "Empresa parceira da FECAP com oportunidades em negócios, marketing, finanças, operações e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Consumo", "Marketing", "Operações"],
  },
  {
    id: "nextel",
    name: "Nextel",
    logo: `${FECAP_LOGO_BASE_URL}/logo-nextel.svg`,
    industry: "Telecomunicações",
    description:
      "Empresa apresentada na relação de organizações parceiras da FECAP.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Telecomunicações"],
  },
  {
    id: "omie",
    name: "Omie",
    logo: `${FECAP_LOGO_BASE_URL}/logo-omie.svg`,
    industry: "Tecnologia e software",
    description:
      "Empresa parceira da FECAP com oportunidades em software, produtos digitais, vendas, dados e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 25,
    tags: ["FECAP", "Software", "SaaS", "Tecnologia"],
  },
  {
    id: "pwc",
    name: "PwC",
    logo: `${FECAP_LOGO_BASE_URL}/logo-pwc.svg`,
    industry: "Auditoria e consultoria",
    description:
      "Empresa parceira da FECAP com oportunidades em auditoria, consultoria, contabilidade, riscos e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Auditoria", "Consultoria", "Tecnologia"],
  },
  {
    id: "queiroz",
    name: "Queiroz",
    logo: `${FECAP_LOGO_BASE_URL}/logo-queiroz.svg`,
    industry: "Serviços empresariais",
    description:
      "Empresa parceira da FECAP com oportunidades profissionais e aproximação com a comunidade acadêmica.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Parceira institucional"],
  },
  {
    id: "randstad",
    name: "Randstad",
    logo: `${FECAP_LOGO_BASE_URL}/logo-randstad.svg`,
    industry: "Recursos humanos",
    description:
      "Empresa parceira da FECAP especializada em recrutamento, seleção, estágio e desenvolvimento de carreira.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "RH", "Recrutamento", "Carreira"],
  },
  {
    id: "santander",
    name: "Santander",
    logo: `${FECAP_LOGO_BASE_URL}/logo-santander.svg`,
    industry: "Serviços financeiros",
    description:
      "Instituição financeira parceira da FECAP com oportunidades em negócios, finanças, dados e tecnologia.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Banco", "Finanças", "Tecnologia"],
  },
  {
    id: "tetra-pak",
    name: "Tetra Pak",
    logo: `${FECAP_LOGO_BASE_URL}/logo-tetra-pak.svg`,
    industry: "Indústria e embalagens",
    description:
      "Empresa parceira da FECAP com oportunidades em indústria, sustentabilidade, negócios, operações e tecnologia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Indústria", "Sustentabilidade"],
  },
  {
    id: "totvs",
    name: "TOTVS",
    logo: `${FECAP_LOGO_BASE_URL}/logo-totvs.svg`,
    industry: "Tecnologia e software",
    description:
      "Empresa parceira da FECAP com oportunidades em desenvolvimento, produtos digitais, dados, cloud e negócios.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Software", "Desenvolvimento", "Cloud"],
  },
  {
    id: "walljobs",
    name: "WallJobs",
    logo: `${FECAP_LOGO_BASE_URL}/logo-walljobs.svg`,
    industry: "Recrutamento e seleção",
    description:
      "Parceira da FECAP voltada a vagas, programas de estágio, trainee e conexão entre estudantes e empresas.",
    isFecapPartner: true,
    partnershipType: "recruitment",
    recommendationBoost: 30,
    tags: ["FECAP", "Vagas", "Estágio", "Trainee"],
  },
  {
    id: "young-and-rubicam",
    name: "Y&R",
    logo: `${FECAP_LOGO_BASE_URL}/logo-y&r.svg`,
    industry: "Publicidade e comunicação",
    description:
      "Empresa parceira da FECAP com oportunidades em publicidade, comunicação, marketing e estratégia.",
    isFecapPartner: true,
    partnershipType: "institutional",
    recommendationBoost: 20,
    tags: ["FECAP", "Publicidade", "Marketing", "Comunicação"],
  },
];